// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connector/grpc/rs.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Code 响应结果码
type Code int32

const (
	// Success 成功
	Code_Success Code = 0
	// Fail 失败
	Code_Fail Code = 1
)

var Code_name = map[int32]string{
	0: "Success",
	1: "Fail",
}

var Code_value = map[string]int32{
	"Success": 0,
	"Fail":    1,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{0}
}

// ReqConf 请求获取数据库引擎对象
type ReqConf struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqConf) Reset()         { *m = ReqConf{} }
func (m *ReqConf) String() string { return proto.CompactTextString(m) }
func (*ReqConf) ProtoMessage()    {}
func (*ReqConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{0}
}

func (m *ReqConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqConf.Unmarshal(m, b)
}
func (m *ReqConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqConf.Marshal(b, m, deterministic)
}
func (m *ReqConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqConf.Merge(m, src)
}
func (m *ReqConf) XXX_Size() int {
	return xxx_messageInfo_ReqConf.Size(m)
}
func (m *ReqConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqConf.DiscardUnknown(m)
}

var xxx_messageInfo_ReqConf proto.InternalMessageInfo

// RespConf 响应获取数据库引擎对象
type RespConf struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Conf 数据库引擎对象
	Conf *Config `protobuf:"bytes,2,opt,name=Conf,proto3" json:"Conf,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespConf) Reset()         { *m = RespConf{} }
func (m *RespConf) String() string { return proto.CompactTextString(m) }
func (*RespConf) ProtoMessage()    {}
func (*RespConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{1}
}

func (m *RespConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespConf.Unmarshal(m, b)
}
func (m *RespConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespConf.Marshal(b, m, deterministic)
}
func (m *RespConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespConf.Merge(m, src)
}
func (m *RespConf) XXX_Size() int {
	return xxx_messageInfo_RespConf.Size(m)
}
func (m *RespConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RespConf.DiscardUnknown(m)
}

var xxx_messageInfo_RespConf proto.InternalMessageInfo

func (m *RespConf) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespConf) GetConf() *Config {
	if m != nil {
		return m.Conf
	}
	return nil
}

func (m *RespConf) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqDatabases 请求获取数据库集合
type ReqDatabases struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDatabases) Reset()         { *m = ReqDatabases{} }
func (m *ReqDatabases) String() string { return proto.CompactTextString(m) }
func (*ReqDatabases) ProtoMessage()    {}
func (*ReqDatabases) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{2}
}

func (m *ReqDatabases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDatabases.Unmarshal(m, b)
}
func (m *ReqDatabases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDatabases.Marshal(b, m, deterministic)
}
func (m *ReqDatabases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDatabases.Merge(m, src)
}
func (m *ReqDatabases) XXX_Size() int {
	return xxx_messageInfo_ReqDatabases.Size(m)
}
func (m *ReqDatabases) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDatabases.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDatabases proto.InternalMessageInfo

// RespDatabases 响应获取数据库集合
type RespDatabases struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Databases 数据库对象集合
	Databases []*Database `protobuf:"bytes,2,rep,name=Databases,proto3" json:"Databases,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespDatabases) Reset()         { *m = RespDatabases{} }
func (m *RespDatabases) String() string { return proto.CompactTextString(m) }
func (*RespDatabases) ProtoMessage()    {}
func (*RespDatabases) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{3}
}

func (m *RespDatabases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespDatabases.Unmarshal(m, b)
}
func (m *RespDatabases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespDatabases.Marshal(b, m, deterministic)
}
func (m *RespDatabases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespDatabases.Merge(m, src)
}
func (m *RespDatabases) XXX_Size() int {
	return xxx_messageInfo_RespDatabases.Size(m)
}
func (m *RespDatabases) XXX_DiscardUnknown() {
	xxx_messageInfo_RespDatabases.DiscardUnknown(m)
}

var xxx_messageInfo_RespDatabases proto.InternalMessageInfo

func (m *RespDatabases) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespDatabases) GetDatabases() []*Database {
	if m != nil {
		return m.Databases
	}
	return nil
}

func (m *RespDatabases) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqForms 请求获取数据库表集合
type ReqForms struct {
	// DatabaseName 数据库名称
	DatabaseName         string   `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqForms) Reset()         { *m = ReqForms{} }
func (m *ReqForms) String() string { return proto.CompactTextString(m) }
func (*ReqForms) ProtoMessage()    {}
func (*ReqForms) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{4}
}

func (m *ReqForms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqForms.Unmarshal(m, b)
}
func (m *ReqForms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqForms.Marshal(b, m, deterministic)
}
func (m *ReqForms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqForms.Merge(m, src)
}
func (m *ReqForms) XXX_Size() int {
	return xxx_messageInfo_ReqForms.Size(m)
}
func (m *ReqForms) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqForms.DiscardUnknown(m)
}

var xxx_messageInfo_ReqForms proto.InternalMessageInfo

func (m *ReqForms) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

// RespForms 响应获取数据库表集合
type RespForms struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Forms 数据库表对象集合
	Forms []*Form `protobuf:"bytes,2,rep,name=Forms,proto3" json:"Forms,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespForms) Reset()         { *m = RespForms{} }
func (m *RespForms) String() string { return proto.CompactTextString(m) }
func (*RespForms) ProtoMessage()    {}
func (*RespForms) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{5}
}

func (m *RespForms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespForms.Unmarshal(m, b)
}
func (m *RespForms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespForms.Marshal(b, m, deterministic)
}
func (m *RespForms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespForms.Merge(m, src)
}
func (m *RespForms) XXX_Size() int {
	return xxx_messageInfo_RespForms.Size(m)
}
func (m *RespForms) XXX_DiscardUnknown() {
	xxx_messageInfo_RespForms.DiscardUnknown(m)
}

var xxx_messageInfo_RespForms proto.InternalMessageInfo

func (m *RespForms) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespForms) GetForms() []*Form {
	if m != nil {
		return m.Forms
	}
	return nil
}

func (m *RespForms) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqCreateDatabase 请求新建数据库
type ReqCreateDatabase struct {
	// Name 数据库名称，根据需求可以随时变化
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Comment 数据库描述
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateDatabase) Reset()         { *m = ReqCreateDatabase{} }
func (m *ReqCreateDatabase) String() string { return proto.CompactTextString(m) }
func (*ReqCreateDatabase) ProtoMessage()    {}
func (*ReqCreateDatabase) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{6}
}

func (m *ReqCreateDatabase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateDatabase.Unmarshal(m, b)
}
func (m *ReqCreateDatabase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateDatabase.Marshal(b, m, deterministic)
}
func (m *ReqCreateDatabase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateDatabase.Merge(m, src)
}
func (m *ReqCreateDatabase) XXX_Size() int {
	return xxx_messageInfo_ReqCreateDatabase.Size(m)
}
func (m *ReqCreateDatabase) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateDatabase.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateDatabase proto.InternalMessageInfo

func (m *ReqCreateDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateDatabase) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

// ReqCreateForm 请求创建表
type ReqCreateForm struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// Name 表名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Comment 表描述
	Comment string `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	// FormType 表类型
	FormType             FormType `protobuf:"varint,4,opt,name=FormType,proto3,enum=api.FormType" json:"FormType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateForm) Reset()         { *m = ReqCreateForm{} }
func (m *ReqCreateForm) String() string { return proto.CompactTextString(m) }
func (*ReqCreateForm) ProtoMessage()    {}
func (*ReqCreateForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{7}
}

func (m *ReqCreateForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateForm.Unmarshal(m, b)
}
func (m *ReqCreateForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateForm.Marshal(b, m, deterministic)
}
func (m *ReqCreateForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateForm.Merge(m, src)
}
func (m *ReqCreateForm) XXX_Size() int {
	return xxx_messageInfo_ReqCreateForm.Size(m)
}
func (m *ReqCreateForm) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateForm.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateForm proto.InternalMessageInfo

func (m *ReqCreateForm) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqCreateForm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateForm) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ReqCreateForm) GetFormType() FormType {
	if m != nil {
		return m.FormType
	}
	return FormType_Siam
}

// ReqKey 请求新建主键
type ReqCreateKey struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Comment 主键结构名，按照规范结构组成的主键字段名称，由对象结构层级字段通过'.'组成，如'i','in.s'
	KeyStructure         string   `protobuf:"bytes,3,opt,name=KeyStructure,proto3" json:"KeyStructure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateKey) Reset()         { *m = ReqCreateKey{} }
func (m *ReqCreateKey) String() string { return proto.CompactTextString(m) }
func (*ReqCreateKey) ProtoMessage()    {}
func (*ReqCreateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{8}
}

func (m *ReqCreateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateKey.Unmarshal(m, b)
}
func (m *ReqCreateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateKey.Marshal(b, m, deterministic)
}
func (m *ReqCreateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateKey.Merge(m, src)
}
func (m *ReqCreateKey) XXX_Size() int {
	return xxx_messageInfo_ReqCreateKey.Size(m)
}
func (m *ReqCreateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateKey.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateKey proto.InternalMessageInfo

func (m *ReqCreateKey) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqCreateKey) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqCreateKey) GetKeyStructure() string {
	if m != nil {
		return m.KeyStructure
	}
	return ""
}

// ReqIndex 请求新建索引
type ReqCreateIndex struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Comment 主键结构名，按照规范结构组成的主键字段名称，由对象结构层级字段通过'.'组成，如'i','in.s'
	KeyStructure         string   `protobuf:"bytes,3,opt,name=KeyStructure,proto3" json:"KeyStructure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateIndex) Reset()         { *m = ReqCreateIndex{} }
func (m *ReqCreateIndex) String() string { return proto.CompactTextString(m) }
func (*ReqCreateIndex) ProtoMessage()    {}
func (*ReqCreateIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{9}
}

func (m *ReqCreateIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateIndex.Unmarshal(m, b)
}
func (m *ReqCreateIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateIndex.Marshal(b, m, deterministic)
}
func (m *ReqCreateIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateIndex.Merge(m, src)
}
func (m *ReqCreateIndex) XXX_Size() int {
	return xxx_messageInfo_ReqCreateIndex.Size(m)
}
func (m *ReqCreateIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateIndex proto.InternalMessageInfo

func (m *ReqCreateIndex) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqCreateIndex) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqCreateIndex) GetKeyStructure() string {
	if m != nil {
		return m.KeyStructure
	}
	return ""
}

// ReqPut 新增数据
type ReqPut struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPut) Reset()         { *m = ReqPut{} }
func (m *ReqPut) String() string { return proto.CompactTextString(m) }
func (*ReqPut) ProtoMessage()    {}
func (*ReqPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{10}
}

func (m *ReqPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPut.Unmarshal(m, b)
}
func (m *ReqPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPut.Marshal(b, m, deterministic)
}
func (m *ReqPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPut.Merge(m, src)
}
func (m *ReqPut) XXX_Size() int {
	return xxx_messageInfo_ReqPut.Size(m)
}
func (m *ReqPut) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPut.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPut proto.InternalMessageInfo

func (m *ReqPut) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqPut) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqPut) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqPut) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespPut 响应新增数据
type RespPut struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespPut) Reset()         { *m = RespPut{} }
func (m *RespPut) String() string { return proto.CompactTextString(m) }
func (*RespPut) ProtoMessage()    {}
func (*RespPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{11}
}

func (m *RespPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespPut.Unmarshal(m, b)
}
func (m *RespPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespPut.Marshal(b, m, deterministic)
}
func (m *RespPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespPut.Merge(m, src)
}
func (m *RespPut) XXX_Size() int {
	return xxx_messageInfo_RespPut.Size(m)
}
func (m *RespPut) XXX_DiscardUnknown() {
	xxx_messageInfo_RespPut.DiscardUnknown(m)
}

var xxx_messageInfo_RespPut proto.InternalMessageInfo

func (m *RespPut) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespPut) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespPut) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqSet 新增数据
type ReqSet struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSet) Reset()         { *m = ReqSet{} }
func (m *ReqSet) String() string { return proto.CompactTextString(m) }
func (*ReqSet) ProtoMessage()    {}
func (*ReqSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{12}
}

func (m *ReqSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSet.Unmarshal(m, b)
}
func (m *ReqSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSet.Marshal(b, m, deterministic)
}
func (m *ReqSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSet.Merge(m, src)
}
func (m *ReqSet) XXX_Size() int {
	return xxx_messageInfo_ReqSet.Size(m)
}
func (m *ReqSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSet proto.InternalMessageInfo

func (m *ReqSet) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqSet) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqSet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqSet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespSet 响应新增数据
type RespSet struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSet) Reset()         { *m = RespSet{} }
func (m *RespSet) String() string { return proto.CompactTextString(m) }
func (*RespSet) ProtoMessage()    {}
func (*RespSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{13}
}

func (m *RespSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSet.Unmarshal(m, b)
}
func (m *RespSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSet.Marshal(b, m, deterministic)
}
func (m *RespSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSet.Merge(m, src)
}
func (m *RespSet) XXX_Size() int {
	return xxx_messageInfo_RespSet.Size(m)
}
func (m *RespSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSet.DiscardUnknown(m)
}

var xxx_messageInfo_RespSet proto.InternalMessageInfo

func (m *RespSet) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespSet) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespSet) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqGet 获取数据
type ReqGet struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGet) Reset()         { *m = ReqGet{} }
func (m *ReqGet) String() string { return proto.CompactTextString(m) }
func (*ReqGet) ProtoMessage()    {}
func (*ReqGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{14}
}

func (m *ReqGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGet.Unmarshal(m, b)
}
func (m *ReqGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGet.Marshal(b, m, deterministic)
}
func (m *ReqGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGet.Merge(m, src)
}
func (m *ReqGet) XXX_Size() int {
	return xxx_messageInfo_ReqGet.Size(m)
}
func (m *ReqGet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGet proto.InternalMessageInfo

func (m *ReqGet) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqGet) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqGet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// RespGet 响应获取数据
type RespGet struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Value Value
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespGet) Reset()         { *m = RespGet{} }
func (m *RespGet) String() string { return proto.CompactTextString(m) }
func (*RespGet) ProtoMessage()    {}
func (*RespGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{15}
}

func (m *RespGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGet.Unmarshal(m, b)
}
func (m *RespGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGet.Marshal(b, m, deterministic)
}
func (m *RespGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGet.Merge(m, src)
}
func (m *RespGet) XXX_Size() int {
	return xxx_messageInfo_RespGet.Size(m)
}
func (m *RespGet) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGet.DiscardUnknown(m)
}

var xxx_messageInfo_RespGet proto.InternalMessageInfo

func (m *RespGet) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespGet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RespGet) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqInsert 新增数据
type ReqInsert struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInsert) Reset()         { *m = ReqInsert{} }
func (m *ReqInsert) String() string { return proto.CompactTextString(m) }
func (*ReqInsert) ProtoMessage()    {}
func (*ReqInsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{16}
}

func (m *ReqInsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInsert.Unmarshal(m, b)
}
func (m *ReqInsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInsert.Marshal(b, m, deterministic)
}
func (m *ReqInsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInsert.Merge(m, src)
}
func (m *ReqInsert) XXX_Size() int {
	return xxx_messageInfo_ReqInsert.Size(m)
}
func (m *ReqInsert) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInsert.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInsert proto.InternalMessageInfo

func (m *ReqInsert) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqInsert) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqInsert) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqInsert) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespInsert 响应新增数据
type RespInsert struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespInsert) Reset()         { *m = RespInsert{} }
func (m *RespInsert) String() string { return proto.CompactTextString(m) }
func (*RespInsert) ProtoMessage()    {}
func (*RespInsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{17}
}

func (m *RespInsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespInsert.Unmarshal(m, b)
}
func (m *RespInsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespInsert.Marshal(b, m, deterministic)
}
func (m *RespInsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespInsert.Merge(m, src)
}
func (m *RespInsert) XXX_Size() int {
	return xxx_messageInfo_RespInsert.Size(m)
}
func (m *RespInsert) XXX_DiscardUnknown() {
	xxx_messageInfo_RespInsert.DiscardUnknown(m)
}

var xxx_messageInfo_RespInsert proto.InternalMessageInfo

func (m *RespInsert) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespInsert) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespInsert) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqSelect 获取数据
type ReqSelect struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// selector 条件选择器
	Selector             *Selector `protobuf:"bytes,3,opt,name=Selector,proto3" json:"Selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqSelect) Reset()         { *m = ReqSelect{} }
func (m *ReqSelect) String() string { return proto.CompactTextString(m) }
func (*ReqSelect) ProtoMessage()    {}
func (*ReqSelect) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{18}
}

func (m *ReqSelect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSelect.Unmarshal(m, b)
}
func (m *ReqSelect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSelect.Marshal(b, m, deterministic)
}
func (m *ReqSelect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSelect.Merge(m, src)
}
func (m *ReqSelect) XXX_Size() int {
	return xxx_messageInfo_ReqSelect.Size(m)
}
func (m *ReqSelect) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSelect.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSelect proto.InternalMessageInfo

func (m *ReqSelect) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqSelect) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqSelect) GetSelector() *Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

// RespSelect 响应获取数据
type RespSelect struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Count 获取数据总条数
	Count int32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	// Value 获取数据结果
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,4,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSelect) Reset()         { *m = RespSelect{} }
func (m *RespSelect) String() string { return proto.CompactTextString(m) }
func (*RespSelect) ProtoMessage()    {}
func (*RespSelect) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{19}
}

func (m *RespSelect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSelect.Unmarshal(m, b)
}
func (m *RespSelect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSelect.Marshal(b, m, deterministic)
}
func (m *RespSelect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSelect.Merge(m, src)
}
func (m *RespSelect) XXX_Size() int {
	return xxx_messageInfo_RespSelect.Size(m)
}
func (m *RespSelect) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSelect.DiscardUnknown(m)
}

var xxx_messageInfo_RespSelect proto.InternalMessageInfo

func (m *RespSelect) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespSelect) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RespSelect) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RespSelect) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqGet 删除数据
type ReqRemove struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRemove) Reset()         { *m = ReqRemove{} }
func (m *ReqRemove) String() string { return proto.CompactTextString(m) }
func (*ReqRemove) ProtoMessage()    {}
func (*ReqRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{20}
}

func (m *ReqRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRemove.Unmarshal(m, b)
}
func (m *ReqRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRemove.Marshal(b, m, deterministic)
}
func (m *ReqRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRemove.Merge(m, src)
}
func (m *ReqRemove) XXX_Size() int {
	return xxx_messageInfo_ReqRemove.Size(m)
}
func (m *ReqRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRemove proto.InternalMessageInfo

func (m *ReqRemove) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqRemove) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqRemove) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// ReqDelete 删除数据
type ReqDelete struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// selector 条件选择器
	Selector             *Selector `protobuf:"bytes,3,opt,name=Selector,proto3" json:"Selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqDelete) Reset()         { *m = ReqDelete{} }
func (m *ReqDelete) String() string { return proto.CompactTextString(m) }
func (*ReqDelete) ProtoMessage()    {}
func (*ReqDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{21}
}

func (m *ReqDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDelete.Unmarshal(m, b)
}
func (m *ReqDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDelete.Marshal(b, m, deterministic)
}
func (m *ReqDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDelete.Merge(m, src)
}
func (m *ReqDelete) XXX_Size() int {
	return xxx_messageInfo_ReqDelete.Size(m)
}
func (m *ReqDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDelete.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDelete proto.InternalMessageInfo

func (m *ReqDelete) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqDelete) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqDelete) GetSelector() *Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

// RespDelete 响应删除数据
type RespDelete struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Count 获取数据总条数
	Count int32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespDelete) Reset()         { *m = RespDelete{} }
func (m *RespDelete) String() string { return proto.CompactTextString(m) }
func (*RespDelete) ProtoMessage()    {}
func (*RespDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{22}
}

func (m *RespDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespDelete.Unmarshal(m, b)
}
func (m *RespDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespDelete.Marshal(b, m, deterministic)
}
func (m *RespDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespDelete.Merge(m, src)
}
func (m *RespDelete) XXX_Size() int {
	return xxx_messageInfo_RespDelete.Size(m)
}
func (m *RespDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_RespDelete.DiscardUnknown(m)
}

var xxx_messageInfo_RespDelete proto.InternalMessageInfo

func (m *RespDelete) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespDelete) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RespDelete) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// Resp 通用响应对象
type Resp struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_674682bf8ffb71fc, []int{23}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *Resp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.Code", Code_name, Code_value)
	proto.RegisterType((*ReqConf)(nil), "api.ReqConf")
	proto.RegisterType((*RespConf)(nil), "api.RespConf")
	proto.RegisterType((*ReqDatabases)(nil), "api.ReqDatabases")
	proto.RegisterType((*RespDatabases)(nil), "api.RespDatabases")
	proto.RegisterType((*ReqForms)(nil), "api.ReqForms")
	proto.RegisterType((*RespForms)(nil), "api.RespForms")
	proto.RegisterType((*ReqCreateDatabase)(nil), "api.ReqCreateDatabase")
	proto.RegisterType((*ReqCreateForm)(nil), "api.ReqCreateForm")
	proto.RegisterType((*ReqCreateKey)(nil), "api.ReqCreateKey")
	proto.RegisterType((*ReqCreateIndex)(nil), "api.ReqCreateIndex")
	proto.RegisterType((*ReqPut)(nil), "api.ReqPut")
	proto.RegisterType((*RespPut)(nil), "api.RespPut")
	proto.RegisterType((*ReqSet)(nil), "api.ReqSet")
	proto.RegisterType((*RespSet)(nil), "api.RespSet")
	proto.RegisterType((*ReqGet)(nil), "api.ReqGet")
	proto.RegisterType((*RespGet)(nil), "api.RespGet")
	proto.RegisterType((*ReqInsert)(nil), "api.ReqInsert")
	proto.RegisterType((*RespInsert)(nil), "api.RespInsert")
	proto.RegisterType((*ReqSelect)(nil), "api.ReqSelect")
	proto.RegisterType((*RespSelect)(nil), "api.RespSelect")
	proto.RegisterType((*ReqRemove)(nil), "api.ReqRemove")
	proto.RegisterType((*ReqDelete)(nil), "api.ReqDelete")
	proto.RegisterType((*RespDelete)(nil), "api.RespDelete")
	proto.RegisterType((*Resp)(nil), "api.Resp")
}

func init() { proto.RegisterFile("connector/grpc/rs.proto", fileDescriptor_674682bf8ffb71fc) }

var fileDescriptor_674682bf8ffb71fc = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x41, 0x4f, 0xdb, 0x4c,
	0x10, 0xfd, 0x92, 0x18, 0x12, 0x4f, 0x00, 0xf1, 0xad, 0xaa, 0xd6, 0xa5, 0xaa, 0x88, 0xf6, 0x14,
	0xa8, 0x64, 0x24, 0x7a, 0xee, 0xa1, 0x84, 0x42, 0x11, 0x6a, 0x85, 0x36, 0x15, 0x52, 0x91, 0x38,
	0x6c, 0x9c, 0x81, 0x46, 0x4a, 0xbc, 0xce, 0xae, 0x83, 0x9a, 0xff, 0xd0, 0x1f, 0x5d, 0xcd, 0xae,
	0xed, 0x24, 0x88, 0xc8, 0xa8, 0x40, 0x6e, 0x9e, 0x79, 0x9e, 0x79, 0xef, 0xcd, 0x6c, 0x9c, 0x85,
	0x37, 0x91, 0x8a, 0x63, 0x8c, 0x52, 0xa5, 0x0f, 0x6e, 0x75, 0x12, 0x1d, 0x68, 0x13, 0x26, 0x5a,
	0xa5, 0x8a, 0xd5, 0x64, 0x32, 0xd8, 0x79, 0x7b, 0x0f, 0xed, 0xcb, 0x54, 0x3a, 0x7c, 0xe7, 0xdd,
	0x3d, 0x28, 0x52, 0xf1, 0xcd, 0xe0, 0xd6, 0x81, 0xdc, 0x87, 0xba, 0xc0, 0x71, 0x47, 0xc5, 0x37,
	0xbc, 0x07, 0x0d, 0x81, 0x26, 0xa1, 0x67, 0xf6, 0x1e, 0xbc, 0x8e, 0xea, 0x63, 0x50, 0x69, 0x55,
	0xda, 0x5b, 0x87, 0x7e, 0x28, 0x93, 0x41, 0x48, 0x09, 0x61, 0xd3, 0x6c, 0x97, 0xe0, 0xf8, 0x26,
	0xa8, 0xb6, 0x2a, 0xed, 0xe6, 0x61, 0x33, 0x83, 0xa9, 0xad, 0xb0, 0x00, 0x7b, 0x0d, 0xeb, 0x5f,
	0xb4, 0xfe, 0x66, 0x6e, 0x83, 0x5a, 0xab, 0xd2, 0xf6, 0x45, 0x16, 0xf1, 0x2d, 0xd8, 0x10, 0x38,
	0x3e, 0x96, 0xa9, 0xec, 0x49, 0x83, 0x86, 0x1b, 0xd8, 0x24, 0xce, 0x22, 0x51, 0x46, 0xfc, 0x01,
	0xfc, 0xe2, 0xdd, 0xa0, 0xda, 0xaa, 0xb5, 0x9b, 0x87, 0x9b, 0xf6, 0x9d, 0x3c, 0x2b, 0x66, 0xf8,
	0x52, 0x11, 0x21, 0x19, 0x1d, 0x9f, 0x28, 0x3d, 0x32, 0x8c, 0xc3, 0x46, 0x5e, 0xf0, 0x5d, 0x8e,
	0x1c, 0xaf, 0x2f, 0x16, 0x72, 0x3c, 0x02, 0x9f, 0x44, 0xba, 0x82, 0xd2, 0xc9, 0xac, 0xd9, 0xf7,
	0x32, 0x71, 0x0e, 0xa7, 0x8c, 0x70, 0xf9, 0xa5, 0xa2, 0x3e, 0xc3, 0xff, 0xb4, 0x08, 0x8d, 0x32,
	0xc5, 0x9c, 0x9d, 0x31, 0xf0, 0xe6, 0x54, 0xd9, 0x67, 0x16, 0x40, 0xbd, 0xa3, 0x46, 0x23, 0x8c,
	0x53, 0x3b, 0x7e, 0x5f, 0xe4, 0x21, 0xff, 0x53, 0xa1, 0x69, 0x66, 0x3d, 0x88, 0xed, 0x31, 0xee,
	0x0a, 0x8e, 0xea, 0xc3, 0x1c, 0xb5, 0x05, 0x0e, 0xb6, 0x07, 0x0d, 0xea, 0xfc, 0x63, 0x9a, 0x60,
	0xe0, 0xd9, 0x11, 0x6c, 0x16, 0x16, 0x29, 0x29, 0x0a, 0x98, 0x6b, 0xbb, 0x6b, 0xa7, 0xe6, 0x1c,
	0xa7, 0x8f, 0x12, 0xb3, 0xe3, 0xda, 0xcf, 0x09, 0x2a, 0x62, 0xaa, 0x3f, 0xc7, 0x69, 0x37, 0xd5,
	0x93, 0x28, 0x9d, 0x68, 0xcc, 0x94, 0x2d, 0xe4, 0x78, 0x0a, 0x5b, 0x05, 0xe7, 0x59, 0xdc, 0xc7,
	0xdf, 0x2b, 0x61, 0x4d, 0x60, 0x5d, 0xe0, 0xf8, 0x62, 0x92, 0x3e, 0x99, 0x6d, 0x1b, 0x6a, 0xe7,
	0x38, 0xcd, 0x48, 0xe8, 0x91, 0xbd, 0x82, 0xb5, 0x4b, 0x39, 0x9c, 0xb8, 0x69, 0x6f, 0x08, 0x17,
	0xf0, 0x2b, 0xfa, 0xd9, 0x9a, 0x84, 0x28, 0x4b, 0x0e, 0x64, 0x00, 0xf5, 0xaf, 0xd2, 0xfc, 0xa2,
	0xae, 0x44, 0xe6, 0x89, 0x3c, 0x5c, 0x7a, 0x12, 0x9d, 0x9b, 0x2e, 0xae, 0xdc, 0x0d, 0x51, 0x3e,
	0xbb, 0x9b, 0x2b, 0xeb, 0xe6, 0xf4, 0x25, 0xdc, 0xf0, 0x4b, 0xa7, 0xfb, 0xb4, 0x5c, 0x77, 0xe1,
	0xbb, 0x3a, 0xe7, 0x7b, 0xa9, 0x66, 0x43, 0x1f, 0x9c, 0xf1, 0x59, 0x6c, 0x50, 0xaf, 0x6e, 0x09,
	0xd7, 0x00, 0x64, 0x26, 0x63, 0x7d, 0xf6, 0x3d, 0xdc, 0x59, 0x4f, 0x5d, 0x1c, 0x62, 0xf4, 0x74,
	0x4f, 0x7b, 0xd0, 0x70, 0x9d, 0x94, 0xb6, 0x34, 0xf9, 0xbf, 0x40, 0x9e, 0x14, 0x05, 0xcc, 0x95,
	0xb3, 0x95, 0x11, 0x97, 0xaf, 0xa9, 0xa3, 0x26, 0xd9, 0x97, 0x75, 0x4d, 0xb8, 0x60, 0x36, 0xaf,
	0xda, 0xc3, 0xcb, 0xf3, 0x16, 0x8c, 0x5e, 0x5b, 0xa3, 0x02, 0x47, 0xea, 0x0e, 0x5f, 0xe0, 0xcc,
	0xb9, 0x39, 0x1e, 0xe3, 0x10, 0x53, 0x5c, 0xe5, 0x1c, 0x7f, 0xba, 0x39, 0x66, 0xc4, 0xff, 0x34,
	0xc7, 0x65, 0x47, 0xe3, 0x13, 0x78, 0xd4, 0xba, 0xac, 0xe9, 0xac, 0xbc, 0x3a, 0x5f, 0xbe, 0x9f,
	0x95, 0xb1, 0x26, 0xd4, 0xbb, 0x93, 0x28, 0x42, 0x63, 0xb6, 0xff, 0x63, 0x0d, 0xf0, 0x4e, 0xe4,
	0x60, 0xb8, 0x5d, 0x39, 0xda, 0x87, 0xdd, 0x28, 0x0e, 0x65, 0x0f, 0xf5, 0x20, 0x0a, 0x87, 0x83,
	0xe1, 0xb4, 0xdf, 0x0b, 0x8b, 0x1b, 0x51, 0x48, 0x37, 0xa2, 0xa3, 0xba, 0xe8, 0x5e, 0xd0, 0x6d,
	0xa8, 0xb7, 0x6e, 0x2f, 0x45, 0x1f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x12, 0x9d, 0xd9, 0x0c,
	0x6c, 0x09, 0x00, 0x00,
}
